version: 0.2

phases:
  pre_build:
    commands:
      - cd startuptoolbag/www/react-frontend
      - echo Running NPM Install
      - pwd
      - npm install
  build:
    commands:
      - echo Running npm build
      - pwd
      - npm run build:quiet
      - cd ../../../
      - pwd
  post_build:
    commands:
      - pwd
      - ls -lh startuptoolbag/www/react-frontend/build
artifacts:
  files:
     - ./*
  base-directory: startuptoolbag/www/react-frontend/build