version: 0.2

phases:
  pre_build:
    commands:
      - cd awsboilerplate/www/react-frontend
      - echo Running NPM Install!!
      - pwd
      - npm install --quiet --no-progress
  build:
    commands:
      - echo Running npm build!!
      - pwd
      - npm run build:dev
      - cd ../../../
      - pwd
  post_build:
    commands:
      - pwd
      - ls -lh awsboilerplate/www/react-frontend/build
      - rm -rf awsboilerplate/www/react-frontend/node_modules
artifacts:
  files:
     - '**/*'