version: 0.2

phases:
  pre_build:
    commands:
      - cd startuptoolbag/www/react-frontend
      - echo Running NPM Install
      - pwd
      - npm install
  build:
    commands:
      - echo Running npm build
      - pwd
      - npm run build:quiet
      - cd ../../../
      - pwd
  post_build:
    commands:
      - ls -lh startuptoolbag/www/react-frontend/build
# Disabling this stage - no need for it as S3Deploy as part of CDK picks it up
#artifacts:
#  files:
#     - ./*
#  base-directory: startuptoolbag/www/react-frontend/build