version: 0.2

phases:
  pre_build:
    commands:
      - cd awsboilerplate/www
      - echo Running NPM Install!!
      - pwd
      - npm install --quiet --no-progress
  build:
    commands:
      - echo Running npm build!!
      - pwd
      - npm run build:prod
      - cd ../../../
      - pwd
  post_build:
    commands:
      - pwd
      - ls -lh awsboilerplate/www/build
      - rm -rf awsboilerplate/www/node_modules
artifacts:
  files:
     - '**/*'